

# language: go 

# go:
#     -1.13


# services:
#   - docker

# before_install:
#   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#   - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#   - sudo apt-get update
#   - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#   - go get github.com/mattn/goveralls


  matrix:
    include:
      - language: node_js
        node_js:
          - stable
        install:
          - cd frontend
          - npm ci
        script:
          - npm run test -- --coverage
        after_script:
          - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
      - language: go
          go:
            - 1.13
          before_install:
            - go get github.com/mattn/goveralls
          script:
            - $GOPATH/bin/goveralls -service=travis-ci
  


# language: node_js
# node_js:
#   - stable
# install:
#   - cd frontend
#   - npm ci

# script:
#   - npm run test -- --coverage
# after_script:
#   - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
