language: go
  go:
    - 1.13
  before_install:
    - go get github.com/mattn/goveralls
  script:
    - $GOPATH/bin/goveralls -service=travis-ci
  


# language: node_js
# node_js:
#   - stable
# install:
#   - cd frontend
#   - npm ci

# script:
#   - npm run test -- --coverage
# after_script:
#   - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
